config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :topics do
  	member do # member做特定物件的事件
      post :like
      post :dislike
      post :add_collection
      post :remove_collection
      post :comments
      delete :del_comment
    end

    collection do
      get :about_us
    end

  end

  resources :users do
    collection do # collection做所有物件的事件（不指定id）
      get :my_posts
      get :my_collections
      delete :del_my_post
    end
  end

  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
    resources :topics
  end

  root "topics#index"
end

app/models/topic.rb
class Topic < ApplicationRecord
	validates_presence_of :title, :content
	delegate :name, :to => :category, :prefix => true, :allow_nil => true
	delegate :email, :to => :user, :prefix => true, :allow_nil => true

	belongs_to :category, optional: true
	belongs_to :user, optional: true

	has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures

  has_many :collections
  has_many :collected_users, through: :collections, source: :user

  def group_by_comments_users
    comments_users = []
    self.comments.each do |j|
      comments_users << j.user.nickname
    end

    return comments_users.uniq
  end

  def find_like(user)
    Like.where( :topic_id => self.id, :user_id => user.id ).first
  end

  def is_liked_by(user)
    find_like(user).present?
  end

  def find_collection(user)
    Collection.where( :topic_id => self.id, :user_id => user.id ).first
  end

  def is_collected_by(user)
    find_collection(user).present?
  end


end

app/controllers/api_v1/topics_controller.rb
class ApiV1::TopicsController < ApiController

	def index
		@topics = Topic.all
    # render json: @topics.to_json

  end

  def show
    @topic = Topic.find_by(id: params[:id]) #find(id)若找不到值會錯誤，但find_by可以自訂錯誤訊息
    if @topic
      # render json: @topic.to_json
    else
      render json: {message: 'fail!'}, status: 400
    end
  end

  def create
    @topic = Topic.new(title: params[:title], content: params[:content])
    if @topic.save
      render json: {message: 'ok!'}
    else
      render json: {message: 'fail!'}, status: 400
    end
  end

  def update
    @topic = Topic.find_by(id: params[:id])
    if @topic.update(title: params[:title], content: params[:content])
      render json: {message: 'ok!'}
    else
      render json: {message: 'fail!'}, status: 400
    end
  end

  def destroy
    @topic = Topic.find_by(id: params[:id])
    if @topic.destroy
      render json: {message: 'ok!'}
    else
      render json: {message: 'fail!'}, status: 400
    end
  end

  # private

  # def topic_params
  #   params.require(:topic).permit(:title, :content)
  # end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	before_action :authenticate_user!, except: [:index, :about_us]
	before_action :find_topic, except: [:index, :new, :create, :about_us]

  # PERMIT_PARAMS = [:comments_sort, :x  , :c ]

	def index
		category = Category.find_by(name: params[:category]) if params[:category]

		@topics = if params[:keyword] #根據keyword篩選
                Topic.where( [ "title like ?", "%#{params[:keyword]}%" ] ).page(params[:page]).per(10)

             	elsif category #根據類別下拉選單篩選
              	category.topics.order("created_at DESC").page(params[:page]).per(10)

##
  # params?.in?PERMIT_PARAMS
##

              elsif params[:comments_sort] #根據使用者點擊留言數的左右箭頭排列ACS/DESC
                if params[:comments_sort] == 'comments_up'
                  Topic.order("comments_num ASC").page(params[:page]).per(10)
                elsif params[:comments_sort] == 'comments_down'
                  Topic.order("comments_num DESC").page(params[:page]).per(10)
                end

              elsif params[:post_sort] #根據使用者點擊建立日期的左右箭頭排列ACS/DESC
                if params[:post_sort] == 'post_up'
                  Topic.order("created_at ASC").page(params[:page]).per(10)
                elsif params[:post_sort] == 'post_down'
                  Topic.order("created_at DESC").page(params[:page]).per(10)
                end

              elsif params[:latest_comment_sort] #根據使用者點擊最新留言的左右箭頭排列ACS/DESC
                if params[:latest_comment_sort] == 'latest_comment_up'
                  Topic.order("latest_comment_time ASC").page(params[:page]).per(10)
                elsif params[:latest_comment_sort] == 'latest_comment_down'
                  Topic.order("latest_comment_time DESC").page(params[:page]).per(10)
                end

              else
                Topic.order("created_at DESC").page(params[:page]).per(10)
              end

	end

	def new
		@topic = Topic.new
    @picture = @topic.pictures.new

	end

	def create
		@topic = Topic.new(topic_params)
		@topic.user = current_user

		if @topic.save
			redirect_to topics_path
			flash[:notice] = "新增成功！"
		else
			render :new
		end

	end

	def show
    @comments = @topic.comments.order("created_at asc")

    if params[:edit_comment_in_topic]
      @comment = @topic.comments.find(params[:edit_comment_in_topic])

      # respond_to do |format|
      #   format.js
      #   format.html {render :show}
      # end

    else
		  @comment = Comment.new
      @picture = @comment.pictures.new

    end

	end

	def edit
    # @picture = @topic.pictures.find(params[:image])
    @picture = @topic.pictures.new

	end

	def update
		if @topic.update(topic_params)
			redirect_to topic_path(@topic)
			flash[:warning] = "更新成功！"
		else
			render :edit
		end

	end

	def destroy
		@topic.destroy

    respond_to do |format|
      # remote: true
      format.js #destroy.js.erb
      format.html {redirect_to topics_path}
    end

		# redirect_to topics_path
		# flash[:alert] = "刪除成功！"
	end

	def comments
		 if params[:edit_comment_in_topic]
      @comment = @topic.comments.find(params[:edit_comment_in_topic])
      @comment.update(comment_params)

      # redirect_to topic_path(@topic)
      respond_to do |format|
        format.js
        format.html {redirect_to topic_path(@topic)}
      end

    else
      @comment = @topic.comments.new(comment_params)
      @comment.user = current_user
      if @comment.save
        @topic.latest_comment_time = @topic.comments.last
        @topic.comments_num = @topic.comments.count
        @topic.save

        respond_to do |format|
          format.js
          format.html {redirect_to topic_path(@topic)}
        end

      else
        render :show

      end
    end


	end

  def edit_comment

  end

  def del_comment
    if params[:del_comment_in_topic]
      @comment = current_user.comments.find(params[:del_comment_in_topic])
      @comment.destroy

      respond_to do |format|
        format.js #執行 del_comment.js.erb
        format.html {redirect_to topic_path(@topic)}
      end

    elsif params[:del_comment_in_my_posts]
      @comment = current_user.comments.find(params[:del_comment_in_my_posts])
      @comment.destroy

      redirect_to my_posts_users_path
    end

  end


  def like
    unless @topic.is_liked_by(current_user)
      Like.create( topic: @topic, user: current_user )
    end

    respond_to do |format|
      format.js
      format.html { redirect_to topic_path(@topic) }
    end

  end

  def dislike
    like = @topic.find_like(current_user)
    like.destroy

    respond_to do |format|
      format.js {render :like}
      format.html { redirect_to topic_path(@topic) }
    end

  end

  def add_collection
    unless @topic.is_collected_by(current_user)
      Collection.create( topic_id: @topic.id, user_id: current_user.id )

    end

    respond_to do |format|
      format.js
      format.html { redirect_to topic_path(@topic) }
    end

  end

  def remove_collection
    collection = @topic.find_collection(current_user)
    collection.destroy

    respond_to do |format|
      format.js {render :add_collection}
      format.html { redirect_to topic_path(@topic) }
    end

  end


	private

	def topic_params
		params.require(:topic).permit(:title, :content, :category_id, :user_id, :latest_comment_time, :comments_num, pictures_attributes: [:image])

	end

	def comment_params
		params.require(:comment).permit(:message, :topic_id, :user_id, pictures_attributes: [:image])
	end

	def find_topic
		@topic = Topic.find(params[:id])

	end

end

app/helpers/api_v1/topics_helper.rb
module ApiV1::TopicsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_collection.html.erb
<% if @topic.is_collected_by(current_user) %>
  <%= link_to "", remove_collection_topic_path(@topic), method: :post, :class => "btn btn-primary fa fa-bookmark", remote: true %>
<% else %>
  <%= link_to "", add_collection_topic_path(@topic), method: :post, :class => "btn btn-default fa fa-bookmark-o", remote: true %>
<% end %>

app/views/topics/_comments.html.erb
<li id="comment-<%= comment.id %>" class="comment_boxes">
  <h4><%= comment.user.nickname %> (<span><%= comment.user.email %></span>) </h4>
  <div class="comment_btns">
    <% if current_user && current_user.is_creator?(comment) %>
      <%= link_to '', topic_path(edit_comment_in_topic: comment), class: "fa fa-pencil btn btn-primary btn-xs", remote: true %>
      <%= link_to '', del_comment_topic_path(del_comment_in_topic: comment), method: :delete, data: {confirm: 'Are you sure ?'}, class: "fa fa-times btn btn-danger btn-xs", remote: true %>
    <% end %>
  </div>
  <span class="pull-right">
    <%= comment.created_at.strftime("%b %d. %Y") %>,
    <%= comment.created_at.strftime("%H:%M:%S") %>(<%= time_ago_in_words(comment.updated_at) %>)
    <!-- time_ago_in_words(time) 可以記錄多久前建立(time : created_at)或多久前更新(time : updated_at) -->
  </span>
  <p><%= comment.message %></p>
  <% if comment.pictures.any? %>
    <% comment.pictures.each do |picture| %>
      <%= image_tag picture.image.thumb.url %>
    <% end %>
  <% end %>
</li>

app/views/topics/_form.html.erb
<%= simple_form_for @topic do |n| %>

	<div class="form-group">
		<ul>
			<li><%= n.input :title, input_html: { class: "form-control"} %></li>
			<li>類別：<%= n.collection_select(:category_id, Category.all, :id, :name, prompt: "請選擇分類") %></li>
      <li>上傳圖片 ：
        <%= n.simple_fields_for :pictures do |l| %>
          <%= l.input :image, as: :file %>
        <% end %>
      </li>
		  <li><%= n.input :content, input_html: { class: "form-control"} %></li>
		</ul>
	</div>
	<%= n.submit 'Confirm', class: "btn btn-primary" %>
	<%= link_to 'Cancel', topics_path, class: "btn btn-default" %>

<% end %>

app/views/topics/_like.html.erb
<% if @topic.is_liked_by(current_user) %>
  <%= link_to "", dislike_topic_path(@topic), method: :post, :class => "btn btn-primary fa fa-thumbs-up", remote: true %>
<% else %>
  <%= link_to "", like_topic_path(@topic), method: :post, :class => "btn btn-default fa fa-thumbs-up", remote: true %>
<% end %>

app/views/topics/add_collection.js.erb
str = "<%=j render partial: "collection" %>"

$("#collect_btn").html(str);

app/views/topics/comments.js.erb
<% if params[:edit_comment_in_topic] %>
  new_message = $('textarea').val();
  $('#comment-<%= @comment.id %> p').text(new_message);
  $('textarea').val("");

<% else %>
  li = "<%=j render :partial => "comments", :locals => { :comment => @comment } %>"
  $('textarea').val("");
  // $('#comments_list').scrollTop($('#comments_list ul:first-child').offset().top);
  $('#comments_list ul').append(li);
  $('#comments_list li:last-child').css('animation', 'rubberBand 1s both');
  $('#comments_list').animate({
      scrollTop: $('#comments_list li').position().top
    });

<% end %> 

app/views/topics/del_comment.js.erb
$('#comment-<%= @comment.id %>').animate({
    height: "0px"
  }, 500, function() {

      $( "#comment-<%= @comment.id %>" ).remove();
})

// $('#comment-<%= @comment.id %>').css({
//   'animation': 'bounceOut 1s both',
//   'padding': 0,
//   'margin': 0,
// }, 1000, function(){
//   $("#comment-<%= @comment.id %>").remove().parent('ul').css('height', 'initial');

// });

$('#comments_count').text('回覆數(<%= @topic.comments.count %>)');

app/views/topics/destroy.js.erb
$('#topic-<%= @topic.id %>').remove();

app/views/topics/edit.html.erb
<h1><%= @topic.title %></h1>

<%= render partial: 'form' %>

app/views/topics/index.html.erb
<h1>Welcome to forum !</h1>

<div class="seachbar text-center">
	<p>
	  <%= form_tag topics_path, method: :get do %>
	    <%= text_field_tag "keyword" %>
	    <%= submit_tag 'Search', class: "fa fa-search btn btn-warning btn-sm" %>
	    <%= link_to 'Cancel Search', topics_path, class: 'btn btn-default btn-sm' %>
	  <% end %>
 	<p>
	  <%= form_tag topics_path, method: :get do %>
	    <%= select_tag "category", options_from_collection_for_select(Category.all, "name", "name", params[:category]), onchange: 'this.form.submit()', prompt: "ALL" %>
	  <!-- 第一個name是指要回傳的參數，第二個name是指要顯示在選項上的欄位為name -->
	  <!-- category = Category.find_by(name: params[:category]) if params[:category]中的name即對應上述第一個回傳參數 -->
	  <!-- 也可回傳:id, 第二行則為 Category.find(params[:category]) -->
	  <% end %>
	</p>
	  Searching keyword : <%= params[:keyword] %>
	</p>
</div>

<div class="new_post text-center">
	<%= link_to '', new_topic_path , class: "fa fa-pencil-square-o btn btn-success btn-sm" %><br>
</div>
<div class="paginate text-center">
	<%= paginate @topics %>
</div>

<table class="table table-hover text-center">
	<thead>
		<tr>
			<th class="text-center">分類</th>
			<th class="text-center">標題</th>
			<th class="text-center">作者</th>
			<th class="text-center">LIKES</th>
			<th class="text-center">
				<%= link_to image_tag("up_arrow.svg", width: 25, border: 0), topics_path(comments_sort: :comments_up) %>
				留言數
				<%= link_to image_tag("down_arrow.svg", width: 25, border: 0), topics_path(comments_sort: :comments_down) %>
			</th>
			<th class="text-center">
				<%= link_to image_tag("up_arrow.svg", width: 25, border: 0), topics_path(post_sort: :post_up) %>
				建立日期
				<%= link_to image_tag("down_arrow.svg", width: 25, border: 0), topics_path(post_sort: :post_down) %>
			</th>
			<th class="text-center">
				<%= link_to image_tag("up_arrow.svg", width: 25, border: 0), topics_path(latest_comment_sort: :latest_comment_up) %>
				最新回覆
				<%= link_to image_tag("down_arrow.svg", width: 25, border: 0), topics_path(latest_comment_sort: :latest_comment_down) %>
			</th>
			<th class="text-center"></th>
		</tr>
	</thead>
	<% @topics.each do |topic| %>
		<tr id="topic-<%= topic.id %>"> <!-- id為了讓Ajax能鎖定要改變的位置在哪 -->
			<td>【<%= topic.category.name %>】</td>
			<td><%= link_to topic.title, topic_path(topic) %></td>
			<td>
				<%= topic.user.nickname %><br>
				(<%= topic.user.email %>)
			</td>
			<td>
				<%= topic.likes.count %>
			</td>
			<td>
				<% if topic.comments_num %>
					<div class="comments_count"><%= topic.comments_num %></div>
				<% else %>
					<div class="comments_count">0</div>
				<% end %>
			</td>
			<td>
				<%= topic.created_at.strftime("%b %d. %Y") %><br>
				<%= topic.created_at.strftime("%H:%M:%S") %>
			</td>
			<td>
				<% if(topic.comments.any?) %>
					<%= topic.comments.last.created_at.strftime("%b %d. %Y") %><br>
					<%= topic.comments.last.created_at.strftime("%H:%M:%S") %>
				<% else %>
					-
				<% end %>
			</td>
			<td>
				<% if current_user && current_user.is_creator?(topic) %>
					<%= link_to '', edit_topic_path(topic), class: "fa fa-pencil btn btn-primary btn-sm" %>
					<%= link_to '', topic_path(topic), class: "fa fa-times btn btn-danger btn-sm", method: :delete, data: {confirm: 'Are you sure ?'}, remote: true %>
				<% end %>
			</td>
		</tr>
	<% end %>
</table>

app/views/topics/like.js.erb
str = "<%=j render partial: "like" %>"

$("#like_btn").html(str);

$("#who_likes").text('Who also like this(<%= @topic.likes.count %>) : \
                      <% @topic.liked_users.each do |like_user| %>\
                        <%= like_user.nickname %>,\
                      <% end %>')

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render partial: 'form' %>

app/views/topics/show.html.erb
 <div class="topic-container">
  <h1>【<%= @topic.category.name %>】<%= @topic.title %></h1>
  <div class="title_bar"></div>

  <%= link_to '', topics_path, class: "fa  fa-chevron-left btn btn-default btn-sm" %>
  <!--<%= link_to '', request.referer.present? ? request.referer : topics_path, class: "fa  fa-chevron-left btn btn-default btn-sm" %> -->
  <% if current_user && current_user.is_creator?(@topic) %>
    <%= link_to '', edit_topic_path(@topic, image: :picture), class: "fa fa-pencil btn btn-primary btn-sm" %>
  <!-- 如果是從其他連結進入此頁面就會返回上一頁，其他皆導回topics_path -->
  <% end %>

  <h4 class="text-center">
    By : <%= @topic.user.email %>
  </h4>

  <p class="topic_content">
    <%= @topic.content %>
  </p>
  <p class="topic_image">
    <% if @topic.pictures.any? %>
      <% @topic.pictures.each do |picture| %>
        <%= image_tag picture.image.thumb.url %>
      <% end %>
    <% else %>
      <%= image_tag "" %>
    <% end %>
  </p>

  <hr>

  <div class="collect_btn">
    <%= render partial: "collection" %>
  </div>

  <div id="like_btn">
    <%= render partial: "like" %>
  </div>
  <h6 id="who_likes">
    Who also like this(<%= @topic.likes.count %>) : <% @topic.liked_users.each do |like_user| %>
      <%= like_user.nickname %>,
    <% end %>
  </h6>

  <hr>

  <p id="comments_users">
    參與回覆者：
    <% @topic.group_by_comments_users.each do |u| %>
      <%= u %>,
    <% end %>
  </p>

  <p id="comments_count">
    回覆數(<%= @comments.count %>)
  </p>
</div>

<div  id="comments_list" class="topic_comments">
  <ul>
    <% @comments.each do |comment| %>
      <%= render partial: 'comments', locals: {comment: comment} %>
    <% end %>
  </ul>
</div>
<%= simple_form_for @comment, url:comments_topic_path(@topic, edit_comment_in_topic: @comment), remote: true, method: :post do |n| %>
<!-- url:comments_topic_path(@topic,m: @comment)後面的m: @comment是在編輯時會把帶進來的文字給一個key m
     好讓controller中的def comments 可以辨識這是新的留言還是編輯舊的留言 -->
  <div class="form-group">
    <%= n.input :message, input_html: { class: "form-control"} %>
  </div>
  <div class="comment_upload">
    <input name="authenticity_token" type="hidden" value="some_long_random_string" />
    <%= n.simple_fields_for :pictures do |l| %>
      <%= l.input :image, as: :file %>
    <% end %>
  </div>
  <%= n.submit 'Post comment', class: "btn btn-success btn-sm", remote: true %>
<% end %>

app/views/topics/show.js.erb
$('textarea').val($('#comment-<%= @comment.id %> p').text());

$("#new_comment").attr("action", "/topics/<%= @topic.id %>/comments/?edit_comment_in_topic=<%= @comment.id %>");
 