config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :topics do
  	member do # member做特定物件的事件
      post :like
      post :dislike
      post :add_collection
      post :remove_collection
      post :comments
      delete :del_comment
    end

    collection do
      get :about_us
    end

  end

  resources :users do
    collection do # collection做所有物件的事件（不指定id）
      get :my_posts
      get :my_collections
      delete :del_my_post
    end
  end

  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
    resources :topics
  end

  root "topics#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  mount_uploader :user_photo, PhotoImageUploader

  has_many :topics
  has_many :comments

  has_many :likes, :dependent => :destroy
  has_many :liked_topics, :through => :likes, :source => :topic

  has_many :collections
  has_many :collected_topics, through: :collections, source: :topic

  def is_creator?(topic)
    topic.user == self

  end

  def self.from_omniauth(auth)
     # Case 1: Find existing user by facebook uid
     user = User.find_by_fb_uid( auth.uid )
     if user
        user.fb_token = auth.credentials.token
        #user.fb_raw_data = auth
        user.save!
       return user
     end

     # Case 2: Find existing user by email
     existing_user = User.find_by_email( auth.info.email )
     if existing_user
       existing_user.fb_uid = auth.uid
       existing_user.fb_token = auth.credentials.token
       #existing_user.fb_raw_data = auth
       existing_user.save!
       return existing_user
     end

     # Case 3: Create new password
     user = User.new
     user.fb_uid = auth.uid
     user.fb_token = auth.credentials.token
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
     #user.fb_raw_data = auth
     user.save!
     return user
   end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_posts
    @my_posts = current_user.topics.page(params[:page]).per(5)
    @my_comments = current_user.comments.order("created_at desc")
  end

  def del_my_post
    @topic = Topic.find(params[:id])
    @topic.destroy

    redirect_to my_posts_users_path

  end

  def my_collections
    @my_likes = current_user.likes.page(params[:page]).per(5)

  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="my_profile_btns text-center">
  <%= link_to 'My profile', users_path, class: "btn btn-warning" %>
  <%= link_to 'My Posts', my_posts_users_path, class: "btn btn-warning" %>
  <%= link_to 'My Collection', my_collections_users_path, class: "btn btn-warning" %>
</div>

<h1 class="text-center">My profile</h1>
<div class="title_bar"></div>

<hr>

<div class="profile_card">
  <div class="photo">
    <%= image_tag current_user.user_photo.url if current_user.user_photo.url %>
  </div>
  <hr>
  <table class="profile_info table table-striped"">
    <tr>
      <th>First name : </th>
      <td></td>
      <td><%= current_user.first_name %></td>
    </tr>
    <tr>
      <th>Last name : </th>
      <td></td>
      <td><%= current_user.last_name %></td>
    </tr>
    <tr>
      <th>Nick name : </th>
      <td></td>
      <td><%= current_user.nickname %></td>
    </tr>
    <tr>
      <th>Email : </th>
      <td></td>
      <td><%= current_user.email %></td>
    </tr>
  </table>
  <div class="text-center">
    <%= link_to '', topics_path, class: 'fa  fa-chevron-left btn btn-default' %>
    <%= link_to '', edit_user_registration_path, class: 'fa  fa-pencil btn btn-primary' %>
  </div>
</div>

app/views/users/my_collections.html.erb
<div class="my_profile_btns text-center">
  <%= link_to 'My profile', users_path, class: "btn btn-warning" %>
  <%= link_to 'My Posts', my_posts_users_path, class: "btn btn-warning" %>
  <%= link_to 'My Collection', my_collections_users_path, class: "btn btn-warning" %>
</div>

<h1 class="text-center">My likes</h1>
<div class="title_bar"></div>
<hr>
<div class="paginate text-center">
  <%= paginate @my_likes %>
</div>
<div class="my_posts">
  <div class="my_view_box">
    <table class="table table-hover text-center">
      <thead>
        <tr>
          <th class="text-center">分類</th>
          <th class="text-center">標題</th>
          <th class="text-center">
            留言數
            <!-- Sorting guide => http://railscasts.com/episodes/228-sortable-table-columns?view=asciicast -->
          </th>
          <th class="text-center">建立日期</th>
          <th class="text-center">最新回覆</th>
        </tr>
      </thead>
      <% @my_likes.each do |t|%>
        <tr>
          <td>【<%= t.topic.category.name %>】</td>
          <td><%= link_to t.topic.title, topic_path(t.topic) %></td>
          <td>
            <div class="comments_count"><%= t.topic.comments.count %></div>
          </td>
          <td>
            <%= t.topic.created_at.strftime("%b %d. %Y") %><br>
            <%= t.topic.created_at.strftime("%H:%M:%S") %>
          </td>
          <td>
            <% if(t.topic.comments.any?) %>
              <%= t.topic.comments.last.created_at.strftime("%b %d. %Y") %><br>
              <%= t.topic.comments.last.created_at.strftime("%H:%M:%S") %>
            <% else %>
              -
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/users/my_posts.html.erb
<div class="my_profile_btns text-center">
  <%= link_to 'My profile', users_path, class: "btn btn-warning" %>
  <%= link_to 'My Posts', my_posts_users_path, class: "btn btn-warning" %>
  <%= link_to 'My Collection', my_collections_users_path, class: "btn btn-warning" %>
</div>

<h1 class="text-center">My posts</h1>
<div class="title_bar"></div>
<hr>
<div class="paginate text-center">
  <%= paginate @my_posts %>
</div>
<div class="my_posts">
  <div class="my_view_box">
    <table class="table table-hover text-center">
      <thead>
        <tr>
          <th class="text-center">分類</th>
          <th class="text-center">標題</th>
          <th class="text-center">
            留言數
            <!-- Sorting guide => http://railscasts.com/episodes/228-sortable-table-columns?view=asciicast -->
          </th>
          <th class="text-center">建立日期</th>
          <th class="text-center">最新回覆</th>
          <th class="text-center"></th>
        </tr>
      </thead>
      <% @my_posts.each do |t|%>
        <tr>
          <td>【<%= t.category.name %>】</td>
          <td><%= link_to t.title, topic_path(t) %></td>
          <td>
            <div class="comments_count"><%= t.comments.count %></div>
          </td>
          <td>
            <%= t.created_at.strftime("%b %d. %Y") %><br>
            <%= t.created_at.strftime("%H:%M:%S") %>
          </td>
          <td>
            <% if(t.comments.any?) %>
              <%= t.comments.last.created_at.strftime("%b %d. %Y") %><br>
              <%= t.comments.last.created_at.strftime("%H:%M:%S") %>
            <% else %>
              -
            <% end %>
          </td>
          <td>
            <% if current_user && current_user.is_creator?(t) %>
              <%= link_to '', edit_topic_path(t), class: "fa fa-pencil btn btn-primary" %>
              <%= link_to '', del_my_post_users_path(id: t), method: :delete, class: "fa fa-times btn btn-danger", data: {confirm: 'Are you sure ?'} %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

<div class="my_comments">
  <h1 class="text-center">My comments</h1>
  <div class="title_bar"></div>
  <div class="my_view_box">
    <ul>
      <% @my_comments.each do |comment| %>
        <li class="col-sm-4">
          <div class="my_comments_box">
            <h4 class="text-center">【<%= comment.topic.category.name %>】<%= comment.topic.title %></h4>
            <h6 class="text-center"><%= comment.created_at.strftime("%b %d. %Y, %H:%M:%S") %></h6>
            <p><%= comment.message %></p>
            <%= link_to '', topic_path(comment.topic), class: "fa fa-search-plus btn btn-warning btn-xs my_read_more" %>
            <%= link_to '', del_comment_topic_path(id: comment.topic_id, del_comment_in_my_posts: comment), method: :delete, data: {confirm: 'Are you sure ?'}, class: "fa fa-times btn btn-danger btn-xs my_delete" %>
            <!-- @my_comments = current_user.comments.order("created_at desc") -->
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<%= link_to '', topics_path, class: 'fa fa-chevron-left btn btn-default' %>