config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :topics do
  	member do # member做特定物件的事件
      post :like
      post :dislike
      post :add_collection
      post :remove_collection
      post :comments
      delete :del_comment
    end

    collection do
      get :about_us
    end

  end

  resources :users do
    collection do # collection做所有物件的事件（不指定id）
      get :my_posts
      get :my_collections
      delete :del_my_post
    end
  end

  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
    resources :topics
  end

  root "topics#index"
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_navbar.html.erb
  <nav class="navbar navbar-reverse">
    <div class="navbar-header">
      <%= link_to '', topics_path, class: 'fa fa-eercast fa-2x navbar-brand' %></a>
    </div>
    <ul class="nav navbar-nav">
      <li>
        <%= link_to 'ABOUT US', about_us_topics_path %>
      </li>
      <li class="dropdown">
        <% if current_user %>
          <a class="btn btn-warning btn-sm dropdown-toggle" data-toggle="dropdown" href="#">
            Hi, <%= current_user.first_name %>(<%= current_user.email %>)
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'My profile', users_path %></li>
            <li><%= link_to('登出', destroy_user_session_path, :method => :delete) %></li>
          </ul>
        <% else %>
          <li><%= link_to('註冊', new_registration_path(:user)) %></li>
          <li><%= link_to('登入', new_session_path(:user)) %></li>
        <% end %>
      </li>
    </ul>


  </nav>